language: ruby
sudo: false

cache: bundler

before_install:
  - sudo apt-get install -qq graphviz
  - gem update --system
  - gem install bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# For Ruby support status see also
# https://www.ruby-lang.org/en/downloads/branches/
#~rvm:
#~  - 2.6
#~  - 2.5
#~  - 2.4

# For Rails support status see also
# https://guides.rubyonrails.org/maintenance_policy.html
#~gemfile:
#~  - gemfiles/activerecord-4.1.Gemfile
#~  - gemfiles/activerecord-4.2.Gemfile
#~  - gemfiles/activerecord-5.0.Gemfile
#~  - gemfiles/activerecord-5.1.Gemfile
#~  - gemfiles/activerecord-5.2.Gemfile
#~  - gemfiles/activerecord-6.0.Gemfile


matrix:
  include:
  - gemfile: gemfiles/activerecord-4.1.Gemfile
    rvm: 2.4

  - gemfile: gemfiles/activerecord-4.2.Gemfile
    rvm: 2.4

  - gemfile: gemfiles/activerecord-5.0.Gemfile
    rvm: 2.3

  - gemfile: gemfiles/activerecord-5.1.Gemfile
    rvm: 2.3

  - gemfile: gemfiles/activerecord-5.2.Gemfile
    rvm: 2.3

  - gemfile: gemfiles/activerecord-6.0.Gemfile
    rvm: 2.6
