language: ruby
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=bb63b568cb7650940fb1d8c8dd647a1760dad052448b4a98078d12fdba62d855

cache: bundler

before_install:
  - sudo apt-get install -qq graphviz
  - gem update --system
  - gem install bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# For Ruby support status see:
#   https://www.ruby-lang.org/en/downloads/branches/
# For Rails support status see:
#   https://guides.rubyonrails.org/maintenance_policy.html
# For valid Ruby-Rails combinations see:
#   https://www.hmallett.co.uk/2018/08/ruby-and-ruby-on-rails-version-compatibility/

matrix:
  include:
  - gemfile: gemfiles/activerecord-4.2.Gemfile
    rvm: 2.4

  - gemfile: gemfiles/activerecord-5.0.Gemfile
    rvm: 2.4

  - gemfile: gemfiles/activerecord-5.1.Gemfile
    rvm: 2.4

  - gemfile: gemfiles/activerecord-5.2.Gemfile
    rvm: 2.4
  - gemfile: gemfiles/activerecord-5.2.Gemfile
    rvm: 2.5

  - gemfile: gemfiles/activerecord-6.0.Gemfile
    rvm: 2.6
